pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: '62404003-b570-4ade-97b6-4b63ac4e5af3', url: 'https://github.com/bhargavpr99-sudo/jenkins-pipeline-example.git']])
                sh "cd my-app && mvn -Dmaven.test.failure.ignore=true clean package"
            }
        }
    }
    post {
        always {
            junit(
                allowEmptyResults:true,
                testResults: 'my-app/target/surefire-reports/*.xml'
            )
        }
    }
}
